package com.hcl.pojos;
// Generated Jun 8, 2021, 2:18:56 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table(name = "pet", catalog = "hcldemo")
public class Pet implements java.io.Serializable {

	private int petid;
	private User user;
	private String petname;
	private Integer petage;
	private String petplace;

	public Pet() {
	}

	public Pet(int petid, String petname) {
		this.petid = petid;
		this.petname = petname;
	}

	public Pet(int petid, User user, String petname, Integer petage, String petplace) {
		this.petid = petid;
		this.user = user;
		this.petname = petname;
		this.petage = petage;
		this.petplace = petplace;
	}

	@Id

	@Column(name = "PETID", unique = true, nullable = false)
	public int getPetid() {
		return this.petid;
	}

	public void setPetid(int petid) {
		this.petid = petid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PETOWNERID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PETNAME", nullable = false, length = 55)
	public String getPetname() {
		return this.petname;
	}

	public void setPetname(String petname) {
		this.petname = petname;
	}

	@Column(name = "PETAGE")
	public Integer getPetage() {
		return this.petage;
	}

	public void setPetage(Integer petage) {
		this.petage = petage;
	}

	@Column(name = "PETPLACE", length = 55)
	public String getPetplace() {
		return this.petplace;
	}

	public void setPetplace(String petplace) {
		this.petplace = petplace;
	}

}
