package com.hcl.pojos;
// Generated Jun 8, 2021, 2:18:56 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "hcldemo", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class User implements java.io.Serializable {

	private int petid;
	private String username;
	private String userpassword;
	private Set pets = new HashSet(0);

	public User() {
	}

	public User(int petid, String username, String userpassword) {
		this.petid = petid;
		this.username = username;
		this.userpassword = userpassword;
	}

	public User(int petid, String username, String userpassword, Set pets) {
		this.petid = petid;
		this.username = username;
		this.userpassword = userpassword;
		this.pets = pets;
	}

	@Id

	@Column(name = "PETID", unique = true, nullable = false)
	public int getPetid() {
		return this.petid;
	}

	public void setPetid(int petid) {
		this.petid = petid;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 55)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "USERPASSWORD", nullable = false, length = 55)
	public String getUserpassword() {
		return this.userpassword;
	}

	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getPets() {
		return this.pets;
	}

	public void setPets(Set pets) {
		this.pets = pets;
	}

}
